---
deployment:
  tasks:
    - /bin/cp -f / "$HOME/public_html/"
    - /bin/cp -f /about "$HOME/public_html/"
    - /bin/cp -f /contact "$HOME/public_html/"
    - /bin/cp -f /faq "$HOME/public_html/"
    - /bin/cp -f process.html "$HOME/public_html/"
    - /bin/cp -f /programme-purpose "$HOME/public_html/"
    - /bin/cp -f /programme-reach "$HOME/public_html/"
    - /bin/cp -f /programme-voice "$HOME/public_html/"
    - /bin/cp -f /programmes "$HOME/public_html/"
    - /bin/cp -f /summit-2026 "$HOME/public_html/"
    - /bin/cp -f /why-us "$HOME/public_html/"
    - /bin/cp -f .htaccess "$HOME/public_html/"
    - /bin/cp -Rf css "$HOME/public_html/"
    - /bin/cp -Rf js "$HOME/public_html/"
    - /bin/cp -Rf images "$HOME/public_html/"