---
deployment:
  tasks:
    - /bin/mkdir -p /home/theipqe/public_html
    - composer install --no-dev --optimize-autoloader --no-interaction
    - /bin/cp -Rf app/. /home/theipqe/public_html/app/
    - /bin/cp -Rf config/. /home/theipqe/public_html/config/
    - /bin/cp -Rf scripts/. /home/theipqe/public_html/scripts/
    - /bin/cp -Rf vendor/. /home/theipqe/public_html/vendor/
    - /bin/cp -f composer.json composer.lock /home/theipqe/public_html/