CREATE TABLE IF NOT EXISTS tis_orders (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    reference VARCHAR(64) NOT NULL,
    access_code VARCHAR(128) DEFAULT NULL,
    full_name VARCHAR(100) NOT NULL,
    email VARCHAR(190) NOT NULL,
    phone VARCHAR(24) NOT NULL,
    tier VARCHAR(24) NOT NULL DEFAULT 'premium',
    amount_kobo INT UNSIGNED NOT NULL,
    ticket_price_kobo INT UNSIGNED NOT NULL,
    secondary_allocation_kobo INT UNSIGNED NOT NULL,
    payment_method VARCHAR(24) NOT NULL,
    status VARCHAR(24) NOT NULL DEFAULT 'pending',
    paystack_id VARCHAR(64) DEFAULT NULL,
    channel VARCHAR(32) DEFAULT NULL,
    paid_at DATETIME DEFAULT NULL,
    ticket_number VARCHAR(40) DEFAULT NULL,
    ticket_token CHAR(48) DEFAULT NULL,
    email_sent_at DATETIME DEFAULT NULL,
    email_lock_at DATETIME DEFAULT NULL,
    email_attempts SMALLINT UNSIGNED NOT NULL DEFAULT 0,
    email_last_error VARCHAR(255) DEFAULT NULL,
    failure_reason VARCHAR(255) DEFAULT NULL,
    client_hash CHAR(64) NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uq_tis_orders_reference (reference),
    UNIQUE KEY uq_tis_orders_ticket_number (ticket_number),
    UNIQUE KEY uq_tis_orders_ticket_token (ticket_token),
    KEY idx_tis_orders_email_created (email, created_at),
    KEY idx_tis_orders_client_created (client_hash, created_at),
    KEY idx_tis_orders_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS tis_ticket_jobs (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    reference VARCHAR(64) NOT NULL,
    status VARCHAR(24) NOT NULL DEFAULT 'queued',
    attempts SMALLINT UNSIGNED NOT NULL DEFAULT 0,
    available_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    locked_at DATETIME DEFAULT NULL,
    completed_at DATETIME DEFAULT NULL,
    last_error VARCHAR(255) DEFAULT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uq_tis_ticket_jobs_reference (reference),
    KEY idx_tis_ticket_jobs_available (status, available_at),
    KEY idx_tis_ticket_jobs_locked (status, locked_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
